name: Deploy to Preview Channel

on:
  pull_request:
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: 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
          firebaseServiceAccount: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAoo/HiC0c4Zwd\nMQtFy14eB4IT0QVYrL78fxOu7T6g6vPQ7sPh7v9SSKZsIEGgfs9EJnc61aQR/w1W\ns4mQRl7xWc/5J3W7/K1nIeZQzcZwtsdvXeP+D/Pednv1X6rRv/VGwKYOtyTE91Fl\ndtv/nUI82ih/Yylvr3I+cQj9bpHNDuvnXppHWqvcfaxer2Uv/ESRRRg2qhEaa0KY\n2VY5zWOys56bk5S8CuAJU2CP7Wf1n/B5aXQjFhvd33n5ObEYOQFDXJne0vygEvCI\n3XRGDsKWYoVn27ErtOBZGdFer8BUnHvpJsr4W5p359DI8Aw36/usO44Ra2y3+3SA\nr/vrGHSXAgMBAAECggEAQqD3skA7ul2ercok6AMrjp9yMoB9pOo7NQKPQFX275nU\ns1OilSchUMioJ4YQrP6vmhbj7omusjrR1kdLMYfllv1Fnhwz8M24/I8RJqnGFX5j\nBPYowduqsiuxPHHWl64ZnFtOFJDsOuSAVuQBvCwcmQesMkOONX8tuMNIJMB11cLV\nkd+fsyJG9Eqbw0AAAw49okpSxTa8vmpUTD/poydxPF6+P+ZXLskucF8F41QvlBYW\nDXwv4cqC9+j6KEw149ZN+WN9F8Ix1gZpskeNrduekTt9XmSfXCwEwXmq/5ZTl2EN\nEhRWiHB177cO+bt8CPEYtTVnx0bk77UQCc82gdr6QQKBgQDsZBbMPXh6xYWYzij6\nAsy3F8UFBqqYdqSNIENcjwpfsBJuPC+QsCyUJu675Xn+LuntAY5ZUGUf7Q4r+MAE\nHUvUvX4rDpAys/HiYiilc8Prv6behLNhazENWVhBKd04TKw+DoMGxISAXfd0kcSn\nRv8c09rAgAY3+C/1Rz+j/4w+fwKBgQDQnUmA8OFPU8FezZpNsEzFtcM8htmjfyaV\nDWLRM6vh3GmvmO96THZ5IYeVDeZwJISo2rdPyiBfyurZh4SsZHNGRoTHrc0jXTJF\nB5FBrrnTk6Btil5R0i9WtYIWuENihHmzUNf6/VOqHQtvImgtpL/b1nT8C0oN3s6G\nx/h+ZWjt6QKBgEccmOsZ9ttf/h+IrTUAkJrnsKIhbkJtNnUp5nm6ohFFA1ZcDqcF\nCHQM/jZSAw/fBwoANNVTZQhkpKW/r+vM8FnwIztKp0BJd5N1meqj16VcwxMfcmL0\n/w2X+f+oW18rWYlVjj8D8SQ4oE9V5oW3ytjeNmlAWh6OL8cmhtOL9aF7AoGAReBp\nfocw8SFc5CR6SwuCq7b2bo+81scAZWzWbLyiFkV+IRNZI9340RoqEANX7LhOt0CL\npm5N6chOYg7CofwDoMZ+M2REElRlQjoGrbmZBQWt9wMiFMYSlTi3GmUeLSGyoh2y\nOqAgJhsUeWVM//zvRvPOu54McBjxlLPmyG+vdgECgYEAq6RFpl9je3i3l8TOlg4N\nGVHwP42JqFw1QmilUXD0UUOZ4ZgDsiTh046c7Yen4tvElj1Vp0BN+ugxiFB7wI5Q\nFwVrSO1Z+VKIdiJUvRPHOhVy+RVzbuIRedqxJMcHNg790nos7lja8k9o1GYLTUPg\nQXHc2hpwb7vSmacmH+ubyro=\n-----END PRIVATE KEY-----\n
          expires: 30d
          projectId: hosting-poc-2a148
